# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7cf078e4652de6408a3aba146ed0e99b2021aaac4e5456b8d897f4d6943969d19ff81f12760c5455c902bdb6c9deb2e85fbeea86cec210b58392da48f13b9f84

test:
  secret_key_base: c01d7630085f337690f38b8c15d1b3671404195cc7e1c9aac8405cb751de304b3c2076478e6c1bbf448f96760faf44f26c1e883ffebb669c3472e9242904586c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
